# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/01DBD3B8458BBAB0/Projects/transinterpreter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/01DBD3B8458BBAB0/Projects/transinterpreter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/01DBD3B8458BBAB0/Projects/transinterpreter/CMakeFiles /mnt/01DBD3B8458BBAB0/Projects/transinterpreter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/01DBD3B8458BBAB0/Projects/transinterpreter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named transinterpreter

# Build rule for target.
transinterpreter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 transinterpreter
.PHONY : transinterpreter

# fast build rule for target.
transinterpreter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/build
.PHONY : transinterpreter/fast

FileReader.o: FileReader.cpp.o
.PHONY : FileReader.o

# target to build an object file
FileReader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/FileReader.cpp.o
.PHONY : FileReader.cpp.o

FileReader.i: FileReader.cpp.i
.PHONY : FileReader.i

# target to preprocess a source file
FileReader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/FileReader.cpp.i
.PHONY : FileReader.cpp.i

FileReader.s: FileReader.cpp.s
.PHONY : FileReader.s

# target to generate assembly for a file
FileReader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/FileReader.cpp.s
.PHONY : FileReader.cpp.s

Interpreter.o: Interpreter.cpp.o
.PHONY : Interpreter.o

# target to build an object file
Interpreter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/Interpreter.cpp.o
.PHONY : Interpreter.cpp.o

Interpreter.i: Interpreter.cpp.i
.PHONY : Interpreter.i

# target to preprocess a source file
Interpreter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/Interpreter.cpp.i
.PHONY : Interpreter.cpp.i

Interpreter.s: Interpreter.cpp.s
.PHONY : Interpreter.s

# target to generate assembly for a file
Interpreter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/Interpreter.cpp.s
.PHONY : Interpreter.cpp.s

LL1Parser.o: LL1Parser.cpp.o
.PHONY : LL1Parser.o

# target to build an object file
LL1Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/LL1Parser.cpp.o
.PHONY : LL1Parser.cpp.o

LL1Parser.i: LL1Parser.cpp.i
.PHONY : LL1Parser.i

# target to preprocess a source file
LL1Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/LL1Parser.cpp.i
.PHONY : LL1Parser.cpp.i

LL1Parser.s: LL1Parser.cpp.s
.PHONY : LL1Parser.s

# target to generate assembly for a file
LL1Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/LL1Parser.cpp.s
.PHONY : LL1Parser.cpp.s

LexicalAnalyzer.o: LexicalAnalyzer.cpp.o
.PHONY : LexicalAnalyzer.o

# target to build an object file
LexicalAnalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/LexicalAnalyzer.cpp.o
.PHONY : LexicalAnalyzer.cpp.o

LexicalAnalyzer.i: LexicalAnalyzer.cpp.i
.PHONY : LexicalAnalyzer.i

# target to preprocess a source file
LexicalAnalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/LexicalAnalyzer.cpp.i
.PHONY : LexicalAnalyzer.cpp.i

LexicalAnalyzer.s: LexicalAnalyzer.cpp.s
.PHONY : LexicalAnalyzer.s

# target to generate assembly for a file
LexicalAnalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/LexicalAnalyzer.cpp.s
.PHONY : LexicalAnalyzer.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/transinterpreter.dir/build.make CMakeFiles/transinterpreter.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... transinterpreter"
	@echo "... FileReader.o"
	@echo "... FileReader.i"
	@echo "... FileReader.s"
	@echo "... Interpreter.o"
	@echo "... Interpreter.i"
	@echo "... Interpreter.s"
	@echo "... LL1Parser.o"
	@echo "... LL1Parser.i"
	@echo "... LL1Parser.s"
	@echo "... LexicalAnalyzer.o"
	@echo "... LexicalAnalyzer.i"
	@echo "... LexicalAnalyzer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

